### ISSUE TITLE
Ruby 2.2.0 breaks tests

### ISSUE THREAD

**Issue by adis-io** [jpastuszek/rspec-background-process#1]
Is project alive?

**Comment by jpastuszek** [comment]
I use it actively. I will have a look.

**Comment by adis-io** [comment]
@jpastuszek 

Cool. I fixed this issue. I changed this line:
`@working_directory || [name, _key],` to this:
`@working_directory || [name.to_s, _key],`
in this line: https://github.com/jpastuszek/rspec-background-process/blob/master/lib/rspec-background-process/process_pool.rb#L117

And tests are passed.

**Comment by jpastuszek** [comment]
Yes, this will do; I have fixed it in other place (to same effect) although not so elegant :/
Anyway I have pushed it to rubygems as v0.1.2.
Looks like mktmpdir does not like Pathname objects instead of String any more.
