### ISSUE TITLE
Background proccess sharing between multiple rspec tests

### ISSUE THREAD

**Issue by miks** [jpastuszek/rspec-background-process#2]
Lets assume that there are feature test with 2 scenarios. 
For first scenario there is background processes defined and running and it is testing some data exchange with background processes.
In second scenario there must be no background processes running to test error handling when system is not fully working.
At the moment I can't find how to scope "rspec-background-process" only for single "it"/"scenario" and stop any background process after test is finished.
Is it possible?

**Comment by jpastuszek** [comment]
I define steps in `Background` scenario like:
```
Given my server
And it is configured xyz
And it is running
```
and if I need it stopped for particular scenario:
```
Given my server is stopped
```

`Given my server` would assign class variable like:
```
	@server = background_process('bin/server', load: true).with do |process|
		process.http_port_allocated_form 1200, 1

		process.argument '--listen', '127.0.0.1'
		process.argument '--port', '<allocated port 1>'

		process.ready_when_log_includes 'Server running'
	end
```
which will be available to all the steps in background and current scenario.
Then in `And it is configured xyz` you can set options:
```
	@server = @server.with do |process|
		process.argument '--config', "<project directory>/#{path}"
	end
```

Finally start it in `And it is running` with:
```
	# crate instance
	@server_instance = @server.instance

	@server_instance.running? ? @server_instance.refresh : (@server_instance.start and @server_instance.wait_ready)
	@server_port = @server_instance.allocated_port(1)
	@server_work_dir = @server_instance.working_directory
```

Then I can send requests to `"localhost:#{@server_port}"`.
You can simply implement `Given my server is stopped` with:
```
	@server.stop
```

Note that here I am using pool of servers with different instances per configuration so I can reuse them between requests if same configuration is requested:
```
require 'rspec-background-process'

Before do
	process_pool(
		#logging: true,
		max_running: 20
	)
end

# run when whole test run is finished
#at_exit do
	#BackgroundProcessCoreHelpers.report_pool_stats
#end
```

You can also use Before/After hooks to run before and after each scenario, see: https://github.com/cucumber/cucumber/wiki/Hooks

I hope this if useful.

**Comment by miks** [comment]
Thanks!
